[package]
name = "json-fmt"
version = "0.2.1"
authors = ["jlinoff <jlinoff@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
